In [1]:
import numpy as np 

## Creating an array using numpy's array() function

In [2]:
array_elements=[[2,9,7],[7,9,2]]
myArray=np.array(array_elements)

In [3]:
myArray

array([[2, 9, 7],
       [7, 9, 2]])

## Creating an array using numpy's zeros() function

In [4]:
myArray2=np.zeros((3,5))

In [5]:
myArray2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

*It creates an array according to the user's input with initial value 0

## Creating an array using numpy's empty() function

In [6]:
myArray3=np.empty((2,4))

In [7]:
myArray3

array([[1.05652183e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.90463839e-310,
        6.90461181e-310]])

*It creates an array according to the user's input with random values

## Creating an array using numpy's empty_like() function

*It creates copy of row and colummns from an existing array(here i am using my exising array called myArray)

In [8]:
myArray4=np.empty_like(myArray)

In [9]:
myArray4

array([[15613248,        0,        0],
       [       0,        0,        0]])

## Creating an array using numpy's arange() function

In [10]:
myArray5=np.arange(20)

In [11]:
myArray5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

*It creates an one dimensional array from 0 to n-1

## Creating an array using numpy's identity() function

In [12]:
myArray6=np.identity(5)

In [13]:
myArray6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

*It gives us the matrix of n x n